### ISSUE TITLE
AttributeError: 'Distribution' object has no attribute 'protoc_version'

### ISSUE THREAD

**Issue by dseomn** [jelmer/setuptools-protobuf#30]
[My build](https://github.com/dseomn/rock-paper-sand/actions/runs/7351771503/job/20015596709) just started failing with the error below. From a glance at https://github.com/jelmer/setuptools-protobuf/pull/25/files it looks like `protoc_version` is set in `load_pyproject_config`, but I'm configuring setuptools-protobuf with setup.py instead of pyproject.toml.

```
       Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          self._add_defaults_build_sub_commands()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 133, in _add_defaults_build_sub_commands
          self.filelist.extend(chain.from_iterable(files))
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 494, in extend
          self.files.extend(filter(self._safe_path, paths))
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 132, in <genexpr>
          files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 131, in <genexpr>
          cmds = (self.get_finalized_command(c) for c in missing_cmds)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 861, in get_command_obj
 cmd_obj = self.command_obj[command] = klass(self)
                                                ^^^^^^^^^^^
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 174, in __init__
          super().__init__(dist)
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 66, in __init__
          self.initialize_options()
        File "/tmp/pip-build-env-bwn4ne78/overlay/lib/python3.11/site-packages/setuptools_protobuf/__init__.py", line 26, in initialize_options
          or get_protoc(getattr(self.distribution, 'protoc_version'))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: 'Distribution' object has no attribute 'protoc_version'
```

**Comment by jelmer** [comment]
load_pyproject_config should always be called, regardless of whether you're using pyproject.toml; how did you update setuptools-protobuf, and what version of setuptools are you using?

**Comment by dseomn** [comment]
> load_pyproject_config should always be called, regardless of whether you're using pyproject.toml

From this code? https://github.com/jelmer/setuptools-protobuf/blob/fdf532174de4a0e39e33943be43af8ab922d1bf6/setuptools_protobuf/__init__.py#L106-L113

Wouldn't that only call `load_pyproject_config` if `pyproject.toml` exists (i.e., no `FileNotFoundError` is raised) and it has a `tool.setuptools-protobuf` section that is truthy in `if cfg:`? In my case, the file does exist, but it doesn't have a `tool.setuptools-protobuf` section. (I'm not all that familiar with TOML or the python build system, so I might be missing something.)

> how did you update setuptools-protobuf

I think it always pulls the latest version from pypi, because https://github.com/dseomn/rock-paper-sand/blob/11f17ee3bc158dc7b049817ead2030886bab3697/pyproject.toml#L18 doesn't specify a version requirement. The test workflow runs weekly, so this should be the first time it picked up 0.1.11 instead of 0.1.10. (I haven't made any changes to the repo in that time period.)

> what version of setuptools are you using?

I don't see anything about the version in the test output, so I assume its either the latest version in pypi (for the same reason as above) or whatever version the github workflow runner already has installed.

**Comment by jelmer** [comment]
Ah, you're right, thanks - fix coming up.
